### ISSUE TITLE
32bit ARM Support

### ISSUE THREAD

**Issue by ttc0419** [database64128/shadowsocks-go#28]
It seems the current implementation can not compile for ARM 32bit.
```
[hello@local shadowsocks-go](main)% env CGO_ENABLED=0 GOARCH=arm GOOS=linux GOARM=7 go build -v -trimpath -ldflags '-s -w' -o ss22 ./cmd/shadowsocks-go
github.com/database64128/shadowsocks-go/mmap
# github.com/database64128/shadowsocks-go/mmap
mmap/mmap_freebsdlinux.go:12:34: undefined: unix.SYS_MMAP
```
Is there something wrong or the implementation hasn't support it yet?

**Comment by database64128** [comment]
Fixed in c7a232431faf7f5d72a77c12421082772ae49c04.

**Comment by ttc0419** [comment]
@database64128 Hi, I'm afraid the issue is not completely fixed.  Just pulled the latest version and build it.  The error is now
```
github.com/database64128/shadowsocks-go/mmap
# github.com/database64128/shadowsocks-go/mmap
mmap/mmap_unixwindows.go:28:15: undefined: readFile
mmap/mmap_unixwindows.go:42:9: undefined: unmap
```

**Comment by database64128** [comment]
My mistake. Should now be fixed in 120ce8abb5d6aedf209ff2828a163989d7ed75c0.
